---
- hosts: ubuntu
  user: "{{ ansible_user }}"
  become: yes

  tasks:
   - name: Actualizar paquetes
     ansible.builtin.apt:
       upgrade: dist
       update_cache: yes
     register: apt_upgrade
     notify: Reinicio server

   - name: Deshabilitar login de root
     ansible.builtin.lineinfile:
       path: /etc/ssh/sshd_config
       regexp: '#PermitRootLogin '
       line: PermitRootLogin no
     notify: Reiniciar ssh

   - name: Deshabilitar inicio de sesion con password
     ansible.builtin.lineinfile:
       path: /etc/ssh/sshd_config
       regexp: '#AuthenticationMethods '
       line: Authenticationmethods publickey
     notify: Reiniciar ssh

   - name: Habilitar inicio con llave publica
     ansible.builtin.lineinfile:
       path: /etc/ssh/sshd_config
       regexp: '#PubkeyAuthentication '
       line: PubkeyAuthentication yes
     notify: Reiniciar ssh

   - name: UFW habilitado y bloqueando trafico
     community.general.ufw:
       state: enabled
       default: deny
       direction: incoming
     when: ansible_facts['os_family'] == "Debian"

   - name: Permitir SSH en UFW
     community.general.ufw:
       rule: allow
       state: enable
       port: ssh
       proto: tcp
     when: ansible_facts['os_family'] == "Debian"

  handlers:
   - name: Reiniciar ssh
     service:
       name: "{{ ssh_service }}"
       state: restarted

   - name: Reinicio server
     ansible.builtin.reboot:
     when: apt_upgrade is changed

...
