---
- hosts: centos
  user: sysadmin
  become: yes

  tasks:

  - name: Chequear servidor NFS este instalado en Centos
    when: ansible_facts['os_family'] == "RedHat"
    yum:
      name: nfs-utils
      state: present

  - name: Asegurar servicio NFS active y enabled
    ansible.builtin.service:
      name: nfs-server
      state: started
      enabled: yes
...


