---
- hosts: centos
  user: " {{ ansible_user }} "
  become: yes

  tasks:

  - name: Chequear servidor NFS este instalado en Centos
    ansible.builtin.package:
      name: "{{ nfs_utils }}"
      state: latest
    notify: reiniciar servicio

  - name: Asegurar servicio NFS active y enabled
    ansible.builtin.service:
      name: nfs-server
      state: started
      enabled: yes

  - name: Habilitar puerto 2049 en firewalld
    ansible.builtin.include_tasks:
      file: fwd.yml
    loop:
      - 2049/tcp

  - name: Chequear que /var/nfs_shared exista, que pertenezca a nobody, y permisos 777
    ansible.builtin.file:
      path: /var/nfs_shared
      state: directory
      owner: nobody
      group: nobody
      mode:  '0777'

  handlers:
    - name: reiniciar servicio
      service:
       name: "{{ nfs_utils }}"
       state: restarted
...




