---
- hosts: centos
  user: " {{ ansible_user }} "
  become: yes

  tasks:

  - name: Chequear servidor NFS este instalado en Centos
    ansible.builtin.package:
      name: "{{ nfs_utils }}"
      state: latest
    notify: Reiniciar NFS_utils

  - name: Asegurar servicio NFS active y enabled
    ansible.builtin.service:
      name: nfs-server
      state: started
      enabled: yes

  - name: Habilitar puerto 2049 en firewalld
    ansible.builtin.include_tasks:
      file: fwd.yml
    loop:
      - 2049/tcp
     # - 111/tcp
     # - 13025/tcp

  - name: Chequear que /var/nfs_shared exista, que pertenezca a nobody, y permisos 777
    ansible.builtin.file:
      path: /var/nfs_shared
      state: directory
      owner: nobody
      group: nobody
      mode:  '0777'

  - name: Modificar puerto /etc/nfs.conf
    ansible.builtin.lineinfile:
      path: /etc/nfs.conf
      line: port=2049
      insertafter: '\[mountd\]'
      state: present

  - name: Asegurar que /var/nfs_shared este en /etc/exports
    ansible.builtin.lineinfile:
      path: /etc/exports
      line: "/var/nfs_shared *(rw,root_squash)"
      state: present
      create: yes
    notify: Reiniciar NFS_Server

  handlers:
    - name: Reiniciar NFS_utils
      service:
        name: "{{ nfs_utils }}"
        state: restarted

    - name: Reiniciar NFS_Server
      service:
        name: "{{ nfs_server }}"
        state: restarted
...




